version: '2'
services:
    web:
        network_mode: host
        build: .
        ports:
            - "2020:2020"
        volumes:
            - .:/app
        environment:
            - MASTER_NODE=http://localhost:3030